Fix documentation, add linter
onflow/cadence pull request #1785
Opened 2022-07-06 04:45 UTC by turbolent

⚠️ Depends on #959 

## Description

- Fix all the broken links
- Add a linter that checks the links and integrate it into CI
______

- [ ] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

2022-07-07 23:06 UTC, 10thfloor requested changes

2022-07-07 23:06 UTC, 10thfloor commented on docs/lint.js
> +documents.forEach(check)
Double trouble?

2022-07-07 23:06 UTC, 10thfloor approved these changes

2022-07-08 00:32 UTC, turbolent commented on .github/workflows/ci.yml
> +    steps:
```suggestion
    runs-on: ubuntu-20.04
    steps:
```

2022-07-08 15:49 UTC, joshuahannan approved these changes
Thanks for fixing all these!

2022-07-08 16:56 UTC, merged