replace docs with links
onflow/cadence pull request #2487
Opened 2023-05-04 20:42 UTC by nialexsan

Closes #???

## Description

replaces docs content with links to their new location in https://github.com/onflow/docs
using script from https://github.com/onflow/docs/pull/46/files#diff-c664086afba767b573a654a57f324cee7c36fe1e9b7a1a02627c642577897871

______

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2023-05-05 19:09 UTC, turbolent commented
@nialexsan let's have a call about Cadence doc migration sometime next week, see https://dapperlabs.slack.com/archives/C01EJE9HVPW/p1683313702183159?thread_ts=1683308997.100439&cid=C01EJE9HVPW

2023-05-10 22:51 UTC, turbolent requested changes
@nialexsan Only user-facing documentation is moved to the onflow/docs repo, documentation for contributors to Cadence will stay here.

*Keep* the files in this repository which were *deleted* in this PR in the docs repo: https://github.com/onflow/docs/pull/58/files

2023-05-15 17:36 UTC, bthaile approved these changes
lgtm

2023-05-15 19:34 UTC, turbolent approved these changes
Thank you for updating all the pages!

2023-05-15 19:36 UTC, merged