trap-check after function called
onflow/cadence pull request #2828
Opened 2023-09-30 05:07 UTC by PratikDhanave

Closes #???

## Description

______

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2023-10-02 14:10 UTC, dsainati1 requested changes
Please update the linked issue with an actual description of what the problem is that isn't just a restatement of the PR title. CI is also failing.

2023-10-02 22:05 UTC, turbolent commented
@PratikDhanave Thank you for your contribution!

Like Daniel asked, could you please clarify what this PR attempts to do?

Why should only traps be handled, and not other errors?

2023-10-02 22:09 UTC, turbolent commented on vm/vm.go
> +	"github.com/bytecodealliance/wasmtime-go/v12"
Why is the PR importing both the `v7` and the `v12` API?

2023-10-02 22:09 UTC, turbolent commented on vm/vm.go
> +		return nil, trap
Why are only traps specifically detected and rejected? What about other kinds of errors?

2023-10-03 04:29 UTC, PratikDhanave commented
@turbolent @dsainati1 sure I will update requested changes

2023-10-06 07:57 UTC, closed without merging