Improve fixed-point multiplication and division
onflow/cadence pull request #490
Opened 2020-12-08 03:24 UTC by turbolent

Use `big.Int` to improve fixed-point multiplication and division.

See https://axiomzen.slack.com/archives/CG0B7CJAJ/p1607115540200500.

2020-12-08 19:22 UTC, tarakby approved these changes
Nice, thanks @turbolent 👌

2020-12-08 20:24 UTC, dete requested changes
Looks good! Do you think we can move `Fix64MaxIntDividend` and `UFix64MaxIntDividend` into the testing files since they are only used there?

2020-12-08 21:09 UTC, turbolent commented
@dete Refactored in d8228adffeb8b6b9377e5b53cf5a884aa3cbe9f8

2020-12-09 03:15 UTC, dete approved these changes

2020-12-09 17:07 UTC, merged